### PR TITLE
Adding support for mongoose 4.0.1 findOneAndUpdate hooks.

### PR DESCRIPTION
**Pull request by rodriguise**
This PR adds support for timestamps when using findOneAndUpdate.

### CODE REVIEW

**Comment by rfink** [comment]
+1

**Comment by michaek** [comment]
This should be merged in, or closed in favor of the re-roll of changes in #28.

**Comment by drudge** [comment]
Merged and published to npm as version 0.5.0. Thanks!

**Comment by michaek** [comment]
Awesome. Thank you!

**Pull request merged**
